export GREP_COLOR="1;33"
export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;44;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;32m'
# export IRCNICK="exiquio"
# export IRCSERVER="irc.freenode.net"
export EDITOR="vim"
# export BROWSER="chromium"
# export RBENV_VERSION="1.9.3-p392"
export MYSQL_HOME="/usr/local/mysql"
export DYLD_LIBRARY_PATH="/usr/local/mysql/lib:$DYLD_LIBRARY_PATH"
export MACPORT_HOME="/opt/local"
export HOMEBREW_HOME="/usr/local"
export RVM_HOME="{$HOME}/.rvm"
export PATH="${MACPORT_HOME}/bin:${HOMEBREW_HOME}/bin:${HOME}/bin:${GEM_HOME}/bin:${RVM_HOME}/bin:${MYSQL_HOME}/bin:${PATH}"
